# Generated by Django 3.2.2 on 2021-07-31 18:04

import casadmin.credentials.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210731_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(error_messages={'blank': 'This field is required.', 'null': 'This field cannot be null.', 'unique': 'A type of bank account with that namealready exists.'}, help_text='Required. 150 characters or fewer.', max_length=150, unique=True, validators=[casadmin.credentials.validators.NameValidator()], verbose_name='name')),
            ],
            options={
                'verbose_name': 'bank account type',
                'verbose_name_plural': 'types of bank accounts',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(error_messages={'blank': 'This field is required.', 'null': 'This field cannot be null.', 'unique': 'A bank with that name already exists.'}, help_text='Required. 50 characters or fewer. Letters and digits and /./- only.', max_length=50, unique=True, validators=[casadmin.credentials.validators.NameValidator()], verbose_name='name')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(error_messages={'blank': 'This field is required.', 'null': 'This field cannot be null.'}, help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='username')),
                ('password', models.CharField(error_messages={'blank': 'This field is required.', 'null': 'This field cannot be null.'}, help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='password')),
                ('login_url', models.CharField(error_messages={'blank': 'This field is required.', 'null': 'This field cannot be null.'}, help_text='Required. 500 characters or fewer.', max_length=500, validators=[casadmin.credentials.validators.UrlValidator()], verbose_name='login URL')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentils',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(error_messages={'blank': 'This field is required.', 'null': 'This field cannot be null.', 'unique': 'A bank account with that name already exists.'}, help_text='Required. 150 characters or fewer.', max_length=150, unique=True, validators=[casadmin.credentials.validators.NameValidator()], verbose_name='name')),
                ('balance', models.IntegerField(default=0, error_messages={'blank': 'This field is required.', 'null': 'This field cannot be null.'}, verbose_name='balance')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.bank', verbose_name='Bank')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.credential', verbose_name='Credential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Type of Account',
                'verbose_name_plural': 'Types of Acounts',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
