version: '3'
services:
    mysql:
        build:
            context: ./Docker/Mysql
        container_name: ${APP_NAME}-mysql
        command: --default-authentication-plugin=mysql_native_password 
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/rollback:/rollback
    web:
        build: 
            context: ./Docker/Web
        container_name: ${APP_NAME}-web
        ports:
            - ${SERVER_PORT}:8000
        command: bash -c "/wait-for-it.sh --timeout=0 mysql:3306 && python manage.py runserver 0.0.0.0:8001"
        volumes:
            - ./src:/src
        depends_on:
            - mysql

